language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - stage: Linting
    script: echo "Fake linting"
    script: echo "another thing"
  - stage: Tests
    script: echo "run test here"
  - stage: deploy
    script: echo "Deploy"
