language: python

services:
  - docker

python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests


stages:
  - lint
  - test
  
jobs:
  include:
    - stage: lint
      name: linting
      script:
        - flake8 *.py
    - stage: test
      name: test
      dist: bionic
      python: 3.8
      script:
        - python -m unittest
