language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests


stages:
  - lint
  - test

script:
  - stage: lint
    script: flake8 *.py
#   - stage: Tests
#     script: echo "run test here"
#   - stage: deploy
#     script: echo "Deploy"
